### ISSUE TITLE
 Get this library into pypi

### ISSUE THREAD

**Issue by marks** [dominodatalab/python-domino#1]
This will make it easier for folks to install. Before this can happen though, we should choose a new package name and namespace as `Domino` is already taken by https://pypi.python.org/pypi/domino/0.1
- [ ] choose new name (@chrismyang)
- [ ] make modifications to code
- [ ] submit to pypi

**Comment by farmdawgnation** [comment]
The name is technically `python-domino`, yes?

We could also name it `dominodatalab` but that seems wordy. `python-domino-api`?

**Comment by tedmiston** [comment]
@marks I'm using the python-domino library in a large-scale project in collaboration with @andscoop and would like to be able to install this from PyPI.  Would you guys be interested in a PR that adds the setup.py etc for publishing `python-domino` releases?

More generally, are you interested in having external collaborators on this repo?  Some additions like mocked unit tests are interesting to us.

**Comment by marks** [comment]
@tedmiston @andscoop - Totally! We'd be very open to reviewing and accepting pull requests for inclusion with pypi, adding tests, etc. Please feel free to let us know if you have any questions at support@dominodatalab.com

**Comment by tedmiston** [comment]
Sounds great.  We'll carve out some time and reach out as needed.

**Comment by ddl-alexpanin** [comment]
Finally in PyPI: https://pypi.org/project/dominodatalab/

**Comment by dknupp** [comment]
> Finally in PyPI: https://pypi.org/project/dominodatalab/

🎉   🙌  🥂
