### ISSUE TITLE
Add upload_file_to_dataset() method

### ISSUE THREAD

**Issue by ZeroCool2u** [dominodatalab/python-domino#171]
Could we add an option to upload files to a Domino Dataset? The CLI is often inconvenient, because it doesn't support headless installations and we don't want to upload files to our code files directory, which is the only option right now via the Python package. There are unfortunately a number of situations in our corporate environment where 'pushing' to Domino is our only choice and we are unable to 'pull' the data via a regular scheduled job in Domino.

**Comment by ddl-alexpanin** [comment]
@ZeroCool2u thanks, I opened a field request for the Data team in our internal JIRA.

**Comment by ZeroCool2u** [comment]
Thank you!

**Comment by ddl-ahmet-gyger** [comment]
Thanks for the feedback @ZeroCool2u - can you share more information on your use case?

**Comment by ZeroCool2u** [comment]
@ddl-ahmet-gyger I can't share more information publicly. Can you sync up with our DDL CSM and Account Exec internally? Our CSM is Tony M and our Account Exec is Chris E. Hopefully you can narrow it down to who they are internally and my workplace, I just don't want to dox them by posting their full names in public. I just briefed them both on this FR in more detail this morning. Feel free to have them schedule some time to chat about this more with me and my team if you'd like as well.

**Comment by ZeroCool2u** [comment]
Closed: Resolved by #185
