### ISSUE TITLE
List users and projects

### ISSUE THREAD

**Issue by russomf** [dominodatalab/python-domino#22]
Ability to list all projects, or all users and all projects given a username.

**Comment by ddl-olsonJD** [comment]
Hello @russomf 

Thank you for this request.
the request to list all projects is fulfilled, with [projects_list[(https://github.com/dominodatalab/python-domino/blob/531468f78fa226c030f4a9d0b4adaa9dbc1f8ce2/domino/domino.py#L727)

if you would still like to see the second part, for all users, completed, please reach out. 
Thank you.
