### ISSUE TITLE
Error when calling files_upload

### ISSUE THREAD

**Issue by andscoop** [dominodatalab/python-domino#33]
When calling files_upload I receive a 400 error if the fp does not have a '/' in front of the name. 
ex.
'test.py'
vs
'/test.py'

Should be an easy fix. Will patch if I find time

**Comment by marks** [comment]
@andscoop this does seem to trip folks up every once in a while. Do you think Domino should return a better error or simply append the preceding `/` for users?

@macrogers @johnjoo1 interested in your thoughts on this one too.

**Comment by peterdcotton** [comment]
I get a 404 error. Do you see anything wrong with this usage...

`def upload_data(local_file,remote_file):
    f = open(local_file, 'rb')
    domino = Domino("peter.cotton/percipience_data",
                api_key='7DunjmBLAHBLAHgzF',
                host='http://app.dominodatalab.com')
    r = domino.files_upload(remote_file, f)
    if r.status_code == 201:
        print(":) Upload successful")
    else:
        print(r.status_code)
        print("!! Upload failed")`

**Comment by ddl-olsonJD** [comment]
resolved in pr
- https://github.com/dominodatalab/python-domino/pull/144
