### ISSUE TITLE
Be able to change compute environment for project

### ISSUE THREAD

**Issue by marks** [dominodatalab/python-domino#35]

**Comment by marks** [comment]
It turns out this is not currently possible through an API-key accessible API at the moment. This is being tracked for "Domino 3.0" API work https://dominodatalab.atlassian.net/browse/DOM-6887 which is slated for release in 2.6.0.

**Comment by ddl-tanner-green** [comment]
This requires further clarification. 
- Is this a default environment for the project as a whole or jut when running a job?
- Is this the compute environment (aka spark compute environments, dask, etc...) or is this just a normal environment for running the main job?

**Comment by ddl-olsonJD** [comment]
Changing jobs environment is possible by passing in the environment id that can be acquired from the `environments_list()`
