### ISSUE TITLE
Add an insecure option for testing purposes

### ISSUE THREAD

**Issue by florian0410** [dominodatalab/python-domino#48]
Hello and thank you for this useful library,
We are currently testing it but we are encountering an issue when trying to request it through https requests:

domino_frontend_address=https://url_of_domino

```bash
Max retries exceeded with url: /version (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

Currently, the code default to verify=True for certificates, we would like to have the possibility to default to False for testing cases before integrating certificates.

If I remember well, it means to add a verify variable to these kind of call:

https://github.com/dominodatalab/python-domino/blob/9f8540eb909e05e3152fd5e9f70107af2672a8ca/domino/domino.py#L77

Can you think about adding these ? Is there an easier way to handle it without changing the code ?

Regards

**Comment by ddl-olsonJD** [comment]
resolving with pr:
- https://github.com/dominodatalab/python-domino/pull/139
