### ISSUE TITLE
runs start via v4 api

### ISSUE THREAD

**Issue by wseaton** [dominodatalab/python-domino#70]
Are there plans to add routes and reimplement `runs_start` and `runs_start_blocking` with the v4 API? I'd like to be able to programatically launch runs with a spark cluster attached.

It'd help if there was public documentation on this endpoint so the rest of the params could be implemented, I had to break out my browser dev tools to figure out the following (which should work in 4.2.2):

Example curl:
```bash
curl 'https://domino.corp.company.com/v4/jobs/start' --data-raw
'{"projectId":"5f3ee18bfe89de5d1160890e",
  "commandToRun": "myscript.py",
  "overrideHardwareTierName": "Tiny (M5)",
  "environmentId": "5f3ee2c3fe89de5d11608a1f", 
"onDemandSparkClusterProperties": 
   {"executorCount": 5,
    "executorHardwareTierId": "tinym5",
    "masterHardwareTierId": "tinym5",
    "computeEnvironmentId": "5f3ac75072a3782602bad37e"}
}'
```

**Comment by abhijeet2096** [comment]
Thanks @wseaton , for bringing this up. We are tracking it internally.

**Comment by ChuckRIHead** [comment]
Hey @wseaton,

The docs are auto-generated and we'll be updating them for our next release. 

In the meantime, I want to make sure you're not blocked. Couldn't quite tell from you issue here. 

Do you have a specific question about the API parameters that I can answer in the meantime?

**Comment by wseaton** [comment]
@ChuckRIHead I'm looking for essentially the complete list of v4 params and a short description of what each does. For example, can I provide a raw command to the v4 api? Before I could do this with `isDirect=True`, now that doesn't seem to be an option.

**Comment by ddl-alexpanin** [comment]
@abhijeet2096 ^^^

**Comment by abhijeet2096** [comment]
Hey @wseaton as part of this draft P.R [here](https://github.com/dominodatalab/python-domino/pull/79/files), we are adding two new methods to start job via V4 API. These methods will include option to add `onDemandSparkCluster` to job. Once this gets completed, you can add wrapper method in airflow operator.

**Comment by abhijeet2096** [comment]
Hey @wseaton the P.R (https://github.com/dominodatalab/python-domino/pull/79) got merged today. It should address this issue.

**Comment by wseaton** [comment]
@abhijeet2096 Thanks, I'll work on a new Operator implementation when I get a chance. Appreciate it!
